apiVersion: v1
kind: Service
metadata:
  name: angular-ssr-app-service
spec:
  selector:
    app: angular-ssr-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
